<?php
	$page = "Términos y condiciones";
	require 'header.php';
?>
<div class="container">
	<div class="row">
		<div class="col s12 m12">
		
		</div>
	</div>
</div>

<div class="container">
            <p class="register-heading"><b>TÉRMINOS Y CONDICIONES DE SERVICIO</b></p>
            <h2><strong>FONDO:</strong></h2>
            <p class="text-justify">
                Estos Términos y Condiciones, junto con cualquier otro documento mencionado en este documento, establecen los términos de uso bajo los cuales puede utilizar este sitio web, <strong> hiscrush.com </strong> ("Nuestro Sitio"). Lea atentamente estos Términos y condiciones y asegúrese de que los comprende. Se considerará que su acuerdo para cumplir y estar sujeto a estos Términos y condiciones se produce cuando utilice por primera vez nuestro Sitio <strong> </strong>. Deberá leer y aceptar estos Términos y condiciones cuando se registre para obtener una Cuenta. Si no está de acuerdo con cumplir con estos Términos y Condiciones, debe dejar de usar Nuestro Sitio inmediatamente.
            </p>
            
            <h2>1. Definiciones e interpretación</h2>
            <p class="text-justify">1.1 In these Terms and Conditions, unless the context otherwise requires, the following expressions have the following meanings:</p>
			<table border="0" cellspacing="0" cellpadding="0">
					<tbody>
						<tr>
							<td>
								<p>
									<strong>“Account”</strong>
								</p>
							</td>
							<td>
								<p>
									means an account required for a User to access certain areas of Our Site, as detailed in Clause 4;
								</p>
							</td>
						</tr>
						<tr>
							<td>
								<p>
									<strong>“Content”</strong>
								</p>
							</td>
							<td>
								<p>
									means any and all text, images, audio, video, scripts, code, software, databases and any other form of information capable of being stored on a computer that appears on, or forms part of, Our Site;
								</p>
							</td>
						</tr>
						<tr>
							<td>
								<p>
									<strong>“Message”</strong>
								</p>
							</td>
							<td>
								<p>
									means any information passed from one User to another User via our System;
								</p>
							</td>
						</tr>
						<tr>
							<td>
								<p>
									<strong>“Post”</strong>
								</p>

								<p>
									<strong>“Submission”</strong>
								</p>
							</td>
							<td>
								<p>
									means any material viewable by others which is generated by a User on Our Site (and includes any and all content in such posts);
								</p>
								<p>
									means Posts or Messages collectively;
								</p>
							</td>
						</tr>
						<tr>
							<td>
								<p>
									<strong>“System”</strong>
								</p>
							</td>
							<td>
								<p>
									means any online communications infrastructure that We make available through Our Site either now or in the future. This may include, but is not limited to, contact forms, email, instant messaging, live chat and Forums;
								</p>
							</td>
						</tr>
						<tr>
							<td>
								<p>
									<strong>“User”</strong>
								</p>
							</td>
							<td>
								<p>
									means a user of Our Site; and
								</p>
							</td>
						</tr>
						<tr>
							<td>
								<p>
									<strong>“We/Us/Our”</strong>
								</p>
							</td>
							<td>
								<p>
									means hiscrush.com.
								</p>
							</td>
						</tr>
					</tbody>
				</table>
            
            <h2>2. Service description</h2>  
            <dl>
                <p class="text-justify">2.1 Welcome to hiscrush.com</p>
                <p class="text-justify">2.2 hiscrush.com is a web-based service that allows the User to create, update, and view an online page known as a CrushTag or Crush Page (herein known as "the Service"). Upon sign up the User is given an account and web address at which their Crush Page can be located, and where the User is allowed to post text, messages, and data or information corresponding, or linked, to images, music, software, graphics, video, etc. (herein known as "the Content"). The Content may reside on the Site's servers or a third party's server.</p>
            </dl>    
            
            <h2>3. Access to Our Site</h2>  
            <dl>
                <p class="text-justify">3.1 Access to Our Site is free of charge.</p>
                <p class="text-justify">3.2 It is your responsibility to make any and all arrangements necessary in order to access Our Site.</p>
                <p class="text-justify">3.3 Access to Our Site is provided “as is” and on an “as available” basis. We may alter, suspend or discontinue Our Site (or any part of it) at any time and without notice. We will not be liable to you in any way if Our Site (or any part of it) is unavailable at any time and for any period.</p>
            </dl>  
            
            <h2>4. Accounts</h2>  
            <dl>
                <p class="text-justify">4.1 Certain parts of Our Site (including the ability to submit material) may require an Account in order to access them.</p>
                <p class="text-justify">4.2 You may not create an Account if you are under 16 years of age. If you are under 16 years of age and wish to use the parts of Our Site that require an Account, your parent or guardian should create the Account for you and you must only use the Account with their supervision. </p>
                <p class="text-justify">4.3 When creating an Account, the information you provide must be accurate and complete. If any of your information changes at a later date, it is your responsibility to ensure that your Account is kept up-to-date. </p>
                <p class="text-justify">4.4 We require that you choose a strong password for your Account. It is your responsibility to keep your password safe. You must not share your Account with anyone else. If you believe your Account is being used without your permission, please contact Us immediately. We will not be liable for any unauthorised use of your Account. </p>
                <p class="text-justify">4.5 You must not use anyone else’s Account. </p>
                <p class="text-justify">4.6 Any personal information provided in your Account will be collected, used, and held in accordance with your rights and Our obligations under applicable laws. </p>
                <p class="text-justify">4.7 If you wish to close your Account, you may do so at any time. Closing your Account will result in the removal of your information. Closing your Account will also remove access to any areas of Our Site requiring an Account for access. </p>
                <p class="text-justify">4.8 If you close your Account, any Submissions you have made on Our Site may be deleted. </p>
            </dl>  
            
            <h2>5. Intellectual Property Rights</h2>  
            <dl>
                <p class="text-justify">5.1 With the exception of Submissions (see Clause 6), all Content on Our Site and the copyright and other intellectual property rights subsisting in that Content, unless specifically labelled otherwise, belongs to or has been licensed by Us. All Content (including Submissions) is protected by its applicable law and international intellectual property laws and treaties. </p>
                <p class="text-justify">5.2 Subject to the licence granted to Us under sub-Clause 6.4, Users retain the ownership of copyright and other intellectual property rights subsisting in Submissions submitted by them (unless any part of such Submissions is owned by a third party who has given their express permission for their material to be used in the Submissions). </p>
                <p class="text-justify">5.3 For personal use (including research and private study) only, you may: </p>
                <p class="text-justify">5.3.1 Access, view and use Our Site in a web browser (including any web browsing capability built into other types of software or app); </p>
                <p class="text-justify">5.3.2 Download Our Site (or any part of it) for caching; </p>
                <p class="text-justify">5.3.3 Print one copy of any page from Our Site; </p>
                <p class="text-justify">5.3.4 Download, copy, clip, print, or otherwise save extracts from pages on Our Site; </p>
                <p class="text-justify">5.3.5 Quote and / or share other Users’ Submissions within Our Site; </p>
                <p class="text-justify">5.3.6 Save pages from Our Site for later and/or offline viewing. </p>
                <p class="text-justify">5.4 You may not use any Content (including Submissions) downloaded, copied, clipped, printed or otherwise saved from Our Site for commercial purposes without first obtaining a licence to do so from Us, our licensors, or from the relevant User, as appropriate. This does not prohibit the normal access, viewing and use of Our Site for general information purposes whether by business users or consumers. </p>
                <p class="text-justify">5.5 You may not systematically copy Content from Our Site with a view to creating or compiling any form of comprehensive collection, compilation, directory, or database unless given Our express permission to do so. </p>
                <p class="text-justify">5.6 Subject to sub-Clauses 5.3 and 5.8 and Clause 6 (governing Submissions) you may not otherwise reproduce, copy, distribute, sell, rent, sub-licence, store, or in any other manner re-use Content or any other material from Our Site unless clearly given express permission to do so. For further information, please contact Us. </p>
                <p class="text-justify">5.7 Our status as the owner and author of the Content on Our Site (or that of identified licensors or Users, as appropriate) must always be acknowledged. </p>
                <p class="text-justify">5.8 Nothing in these Terms and Conditions limits or excludes the fair dealing provisions of Copyright Law, covering in particular the making of temporary copies; research and private study; the making of copies for text and data analysis for non-commercial research; criticism, review, quotation and news reporting; caricature, parody or pastiche; and the incidental inclusion of copyright material. </p>
            </dl>   
            
            <h2>6. Submissions, Messages and Posts</h2>
            <dl>
                <p class="text-justify">6.1 An Account is required if you wish to submit Messages and / or Posts on Our Site. Please refer to Clause 4 for more information.</p>
                <p class="text-justify">6.2 You agree that you will be solely responsible for any such submission. Specifically, you agree, represent and warrant that you have the right to use the content and that your submission will comply with Our Acceptable Usage Policy, detailed below in Clause 7.</p>
                <p class="text-justify">6.3 You agree that you will be liable to Us and will, to the fullest extent permissible by law, indemnify Us for any breach of the warranties given by you under sub-Clause 6.2. You will be responsible for any loss or damage suffered by Us as a result of such breach.</p>
                <p class="text-justify">6.4 You (or your licensors, as appropriate) retain ownership of the content of your submission and all intellectual property rights subsisting therein. By submitting content in this way, you grant Us an unconditional, non-exclusive, fully transferable, royalty-free, perpetual, irrevocable, worldwide licence to use, store, archive, syndicate, publish, transmit, adapt, edit, reproduce, distribute, prepare derivative works from, display, perform and sub-licence the content of your content for the purposes of operating and promoting Our Site.</p>
                <p class="text-justify">6.5 If you wish to remove such material, you may do so by deleting it. Your submission will be deleted. Please note that caching or references to your submission(s) may not be made immediately unavailable (or may not be made unavailable at all where they are outside of Our reasonable control).</p>
                <p class="text-justify">6.6 We may reject, reclassify, or remove any content submitted to Our Site where, in Our sole opinion, the content violates Our Acceptable Usage Policy, or if We receive a complaint from a third party and determine that the submission(s) in question should be removed as a result.</p>
            </dl>
            
            <h2>7. Acceptable Usage Policy</h2>
            <dl>
                <p class="text-justify">7.1 You may only use Our Site in a manner that is lawful and that complies with the provisions of this Clause 7. Specifically:</p>
                <p class="text-justify">7.1.1 you must ensure that you comply fully with any and all applicable local, national and international laws and/or regulations;</p>
                <p class="text-justify">7.1.2 you must not use Our Site in any way, or for any purpose, that is unlawful or fraudulent;</p>
                <p class="text-justify">7.1.3 you must not use Our Site to knowingly send, upload, or in any other way transmit data that contains any form of virus or other malware, or any other code designed to adversely affect computer hardware, software, or data of any kind; and</p>
                <p class="text-justify">7.1.4 you must not use Our Site in any way, or for any purpose, that is intended to harm any person or persons in any way.</p>
                <p class="text-justify">7.2 When submitting content (or communicating in any other way using Our Site), you must not submit, communicate or otherwise do anything that:</p>
                <p class="text-justify">7.2.1 is obscene, deliberately offensive, hateful or otherwise inflammatory;</p>
                <p class="text-justify">7.2.2 promotes violence;</p>
                <p class="text-justify">7.2.3 promotes or assists in any form of unlawful activity;</p>
                <p class="text-justify">7.2.4 discriminates against, or is in any way defamatory of, any person, group or class of persons, race, sex, religion, nationality, disability, sexual orientation or age;</p>
                <p class="text-justify">7.2.5 is intended or otherwise likely to threaten, harass, annoy, alarm, inconvenience, upset, or embarrass another person;</p>
                <p class="text-justify">7.2.6 is calculated or is otherwise likely to deceive;</p>
                <p class="text-justify">7.2.7 is intended or otherwise likely to infringe (or threaten to infringe) another person’s right to privacy;</p>
                <p class="text-justify">7.2.8 misleadingly impersonates any person or otherwise misrepresents your identity or affiliation in a way that is calculated to deceive (obvious parodies are not included within this definition provided that they do not fall within any of the other provisions of this sub-Clause 7.2);</p>
                <p class="text-justify">7.2.9 implies any form of affiliation with Us where none exists;</p>
                <p class="text-justify">7.2.10 infringes, or assists in the infringement of, the intellectual property rights (including, but not limited to, copyright, patents, trade marks and database rights) of any other party; or</p>
                <p class="text-justify">7.2.11 is in breach of any legal duty owed to a third party including, but not limited to, contractual duties and duties of confidence.</p>
                <p class="text-justify">7.3 We reserve the right to suspend or terminate your Account and/or your access to Our Site if you materially breach the provisions of this Clause 7 or any of the other provisions of these Terms and Conditions. Specifically, We may take one or more of the following actions:</p>
                <p class="text-justify">7.3.1 suspend, whether temporarily or permanently, your Account and/or your right to access Our Site;</p>
                <p class="text-justify">7.3.2 remove any material submitted by you that violate(s) this Acceptable Usage Policy;</p>
                <p class="text-justify">7.3.3 issue you with a written warning;</p>
                <p class="text-justify">7.3.4 take legal proceedings against you for reimbursement of any and all relevant costs on an indemnity basis resulting from your breach;</p>
                <p class="text-justify">7.3.5 take further legal action against you as appropriate;</p>
                <p class="text-justify">7.3.6 disclose such information to law enforcement authorities as required or as We deem reasonably necessary; and/or</p>
                <p class="text-justify">7.3.7 any other actions that We deem reasonably appropriate (and lawful).</p>
                <p class="text-justify">7.4 We hereby exclude any and all liability arising out of any actions (including, but not limited to those set out above) that We may take in response to breaches of these Terms and Conditions.</p>
                <p class="text-justify">7.5 We draw your attention to the anonymity inherent in our messaging system however and make you aware that you are not anonymous to Us, nor will you be anonymous to the appropriate bodies and authorities if you breach Our Acceptable Usage Policy.</p>
            </dl>

            <h2>8. Links to Our Site</h2>
            <dl>
                <p class="text-justify">8.1 You may link to Our Site provided that:</p>
                <p class="text-justify">8.1.1 you do so in a fair and legal manner;</p>
                <p class="text-justify">8.1.2 you do not do so in a manner that suggests any form of association, endorsement or approval on Our part where none exists;</p>
                <p class="text-justify">8.1.3 you do not use any logos or trade marks displayed on Our Site without Our express written permission; and</p>
                <p class="text-justify">8.1.4 you do not do so in a way that is calculated to damage Our reputation or to take unfair advantage of it.</p>
                <p class="text-justify">8.2 You may link to any page of Our Site.</p>
                <p class="text-justify">8.3 Framing or embedding of Our Site on other websites is not permitted without Our express written permission. Please contact Us for further information.</p>
                <p class="text-justify">8.4 You may not link to Our Site from any other site the content of which contains material that:</p>
                <p class="text-justify">8.4.1 is obscene, deliberately offensive, hateful or otherwise inflammatory;</p>
                <p class="text-justify">8.4.2 promotes violence;</p>
                <p class="text-justify">8.4.3 promotes or assists in any form of unlawful activity;</p>
                <p class="text-justify">8.4.4 discriminates against, or is in any way defamatory of, any person, group or class of persons, race, sex, religion, nationality, disability, sexual orientation, or age;</p>
                <p class="text-justify">8.4.5 is intended or is otherwise likely to threaten, harass, annoy, alarm, inconvenience, upset, or embarrass another person;</p>
                <p class="text-justify">8.4.6 is calculated or is otherwise likely to deceive another person;</p>
                <p class="text-justify">8.4.7 is intended or is otherwise likely to infringe (or to threaten to infringe) another person’s privacy;</p>
                <p class="text-justify">8.4.8 misleadingly impersonates any person or otherwise misrepresents the identity or affiliation of a particular person in a way that is calculated to deceive (obvious parodies are not included in this definition provided that they do not fall within any of the other provisions of this sub-Clause 8.4);</p>
                <p class="text-justify">8.4.9 implies any form of affiliation with Us where none exists;</p>
                <p class="text-justify">8.4.10 infringes, or assists in the infringement of, the intellectual property rights (including, but not limited to, copyright, trade marks and database rights) of any other party; or</p>
                <p class="text-justify">8.4.11 is made in breach of any legal duty owed to a third party including, but not limited to, contractual duties and duties of confidence.</p>
                <p class="text-justify">8.5 The content restrictions in sub-Clause 8.4 do not apply to content submitted to sites by other users provided that the primary purpose of the site accords with the provisions of sub-Clause 8.4. You are not, for example, prohibited from posting links on general-purpose social networking sites merely because another user may post such content. You are, however, prohibited from posting links on websites which focus on or encourage the submission of such content from users.</p>
            </dl>
            
            <h2>9. Links to Other Sites</h2>
            <dl>
                <p class="text-justify">Links to other sites may be included on Our Site. Unless expressly stated, these sites are not under Our control. We neither assume nor accept responsibility or liability for the content of third party sites. The inclusion of a link to another site on Our Site is for information only and does not imply any endorsement of the sites themselves or of those in control of them.</p>
            </dl>
            
            <h2>10. Advertising</h2>
            <dl>
                <p class="text-justify">We may feature advertising on Our Site. We are not responsible for the content of any advertising on Our Site. Each advertiser is responsible for the content of their own advertising material. We will not be responsible for any advertising on Our Site including, but not limited to, any errors, inaccuracies, or omissions.</p>
            </dl>
            
            <h2>11. Disclaimers and Legal Rights</h2>
            <dl>
                <p class="text-justify">11.1 Nothing on Our Site constitutes advice on which you should rely. It is provided for general information purposes only.</p>
                <p class="text-justify">11.2 Insofar as is permitted by law, We make no representation, warranty, or guarantee that Our Site will meet your requirements, that it will not infringe the rights of third parties, that it will be compatible with all software and hardware, or that it will be secure.</p>
                <p class="text-justify">11.3 If, as a result of Our failure to exercise reasonable care and skill, any digital content from Our Site damages your device or other digital content belonging to you, as a consumer you may be entitled to certain legal remedies. For more details concerning your rights and remedies as a consumer, please contact appropriate advisory services.</p>
                <p class="text-justify">11.4 We make reasonable efforts to ensure that Our Content on Our Site is complete, accurate, and up-to-date. We do not, however, make any representations, warranties or guarantees (whether express or implied) that the Content is complete, accurate, or up-to-date.</p>
                <p class="text-justify">11.5 We are not responsible for the content or accuracy, or for any opinions, views, or values expressed in any Submissions submitted by Users. Any such opinions, views, or values are those of the relevant User, and do not reflect Our opinions, views, or values in any way.</p>
            </dl>
            <h2>12. Our Liability</h2>
            <dl>
                <p class="text-justify">
                    12.1 To the fullest extent permissible by law, We accept no liability to any User for any loss or damage, whether foreseeable or otherwise, in contract, tort (including negligence), for breach of statutory duty, or otherwise, arising out of or in connection with the use of (or inability to use) Our Site or the use of or reliance upon any Content (whether that Content is provided by Us or whether it is in the form of Submissions submitted by Users) included on Our Site.
                </p>
                <p class="text-justify">
                    12.2 To the fullest extent permissible by law, We exclude all representations, warranties, and guarantees (whether express or implied) that may apply to Our Site or any Content (including Submissions) included on Our Site.
                </p>
                <p class="text-justify">
                    12.3 Our Site is intended for non-commercial use only. If you are a business user, We accept no liability for loss of profits, sales, business or revenue; loss of business opportunity, goodwill or reputation; loss of anticipated savings; business interruption; or for any indirect or consequential loss or damage.
                </p>
                <p class="text-justify">
                    12.4 We exercise all reasonable skill and care to ensure that Our Site is free from viruses and other malware, however subject to sub-Clause 11.3, We accept no liability for any loss or damage resulting from a virus or other malware, a distributed denial of service attack, or other harmful material or event that may adversely affect your hardware, software, data or other material that occurs as a result of your use of Our Site (including the downloading of any Content (including any provided in Submissions) from it) or any other site referred to on Our Site.
                </p>
                <p class="text-justify">
                    12.5 We neither assume nor accept responsibility or liability arising out of any disruption or non-availability of Our Site resulting from external causes including, but not limited to, ISP equipment failure, host equipment failure, communications network failure, natural events, acts of war, or legal restrictions and censorship.
                </p>
                <p class="text-justify">
                    12.6 Nothing in these Terms and Conditions excludes or restricts Our liability for fraud or fraudulent misrepresentation, for death or personal injury resulting from negligence, or for any other forms of liability which cannot be excluded or restricted by law. For full details of consumers’ legal rights, including those relating to digital content, please contact appropriate advisory services.
                </p>
                <p class="text-justify">
                    12.7 The Content
                </p>
                <p class="text-justify">
                    The User agrees to obide by the following guidelines when adding content to the site:
                </p>
                <p class="text-justify">
                    1. All content being posted to hiscrush.com in any manner, are the responsibility and property of the author. The Site makes every effort in assuring that the Content is of decency. The Site is not responsible for monitoring or filtering the Content found within or linked on the Site. Individuals posting questionable material accept that they are solely responsible.
                </p>
                <p class="text-justify">
                    2. The Site will take any necessary actions upon the User's account if the User's account has been reported to be offensive in any manner.
                </p>
                <p class="text-justify">
                    3. The Site does not claim ownership or control over what the User posts within any part of the Service. The author retains all patents, copyrights, and trademarks contained in the Content and is solely responsible for protecting those rights.
                </p>
                <p class="text-justify">
                    4. The Site reserves the right to publish any of the Content posted by the User according to the security setting the User has set on the Content.
                </p>
                <p class="text-justify">
                    5. The User understands that the Site does not monitor or filter the Content being posted to any part of the Service. The Site reserves the right to monitor and/or filter the Content being posted to the Site if any concerns arise by the Site or by the User.
                </p>
                <p class="text-justify">
                    12.8 Disclaimer of Warranties
                </p>
                <p class="text-justify">
                    YOU EXPRESSLY UNDERSTAND AND AGREE THAT:
                </p>
                <p class="text-justify">
                    (a) YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. hiscrush.com EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
                </p>
                <p class="text-justify">
                    (b) hiscrush.com MAKES NO WARRANTY THAT (i) THE SERVICE WILL MEET YOUR REQUIREMENTS, (ii) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS, AND (V) ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED.
                </p>
                <p class="text-justify">
                    (c) ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.
                </p>
                <p class="text-justify">
                    (d) NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM hiscrush.com OR THROUGH OR FROM THE SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TERMS OF SERVICE.
                </p>
                <p class="text-justify">
                    12.9 Limitation of Liability -
                </p>
                <p class="text-justify">
                    YOU EXPRESSLY UNDERSTAND AND AGREE THAT hiscrush.com SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF hiscrush.com HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SERVICE; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICE; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; OR (v) ANY OTHER MATTER RELATING TO THE SERVICE.
                </p>
            </dl>
            <h2>13. Viruses, Malware and Security</h2>
            <dl>
                <p class="text-justify">
                    13.1 We exercise all reasonable skill and care to ensure that Our Site is secure and free from viruses and other malware.
                </p>
                <p class="text-justify">
                    13.2 You are responsible for protecting your hardware, software, data and other material from viruses, malware, and other internet security risks.
                </p>
                <p class="text-justify">
                    13.3 You must not deliberately introduce viruses or other malware, or any other material which is malicious or technologically harmful either to or via Our Site.
                </p>
                <p class="text-justify">
                    13.4 You must not attempt to gain unauthorised access to any part of Our Site, the server on which Our Site is stored, or any other server, computer, or database connected to Our Site.
                </p>
                <p class="text-justify">
                    13.5 You must not attack Our Site by means of a denial of service attack, a distributed denial of service attack, or by any other means.
                </p>
                <p class="text-justify">
                    13.6 By breaching the provisions of sub-Clauses 13.3 to 13.5 you may be committing a criminal offence. Any and all such breaches will be reported to the relevant law enforcement authorities and We will cooperate fully with those authorities by disclosing your identity to them. Your right to use Our Site will cease immediately in the event of such a breach.
                </p>
            </dl>
            <h2>14. Privacy and Cookies</h2>
            <dl>
                <p class="text-justify">
                    Use of Our Site is also governed by Our Privacy Policy. This policy is incorporated into these Terms and Conditions by this reference. The User may view the Site's privacy policy in full at
                    <a href="/privacy.php" title="Privacy Information">
    https://www.hiscrush.com/privacy.php
</a> .
                </p>
            </dl>
            <h2>15. Data Protection</h2>
            <dl>
                <p class="text-justify">
                    15.1 All personal information that We may collect (including, but not limited to, your name and contact details) will be collected, used and held in accordance with the provisions of relevant legislation.
                </p>
                <p class="text-justify">
                    15.2 We may use your personal information to:
                </p>
                <p class="text-justify">
                    15.2.1 Provide and administer your Account;
                </p>
                <p class="text-justify">
                    15.2.2 Reply to any communications you send to Us;
                </p>
                <p class="text-justify">
                    15.2.3 Send you important notices, as detailed in Clause 16;
                </p>
                <p class="text-justify">
                    15.3 We will not pass on your personal information to any third parties without first obtaining your express permission to do so<strong>.</strong>
                </p>
            </dl>
            <h2>16. Communications from Us</h2>
            <dl>
                <p class="text-justify">
                    16.1 If you have an Account, We may from time to time send you important notices by email. Such notices may relate to matters including, but not limited to, service changes, changes to these Terms and Conditions, and changes to your Account.
                </p>
                <p class="text-justify">
                    16.2 We will never send you marketing emails of any kind without your express consent. If you do give such consent, you may opt out at any time. Any and all marketing emails sent by Us include an unsubscribe link. If you opt out of receiving emails from Us at any time, it may take up to 7 business days for your new preferences to take effect.
                </p>
                <p class="text-justify">
                    16.3 For questions or complaints about communications from Us (including, but not limited to marketing emails), please contact Us.
                </p>
            </dl>
            <h2>17. Changes to these Terms and Conditions</h2>
            <dl>
                <p class="text-justify">
                    17.1 We may alter these Terms and Conditions at any time. Any such changes will become binding on you upon your first use of Our Site after the changes have been implemented. You are therefore advised to check this page from time to time.
                </p>
                <p class="text-justify">
                    17.2 In the event of any conflict between the current version of these Terms and Conditions and any previous version(s), the provisions current and in effect shall prevail unless it is expressly stated otherwise.
                </p>
            </dl>
            <h2>18. Law and Jurisdiction</h2>
            <dl>
                <p class="text-justify">
                    18.1 These Terms and Conditions, and the relationship between you and Us (whether contractual or otherwise) shall be governed by, and construed in accordance with, Israeli. law.
                </p>
                <p class="text-justify">
                    18.2 If you are a consumer, any disputes concerning these Terms and Conditions, the relationship between you and Us, or any matters arising therefrom or associated therewith (whether contractual or otherwise) shall be subject to the jurisdiction of the Federal courts of Israel, as determined by your residency.
                </p>
                <p class="text-justify">
                    18.3 If you are a business, any disputes concerning these Terms and Conditions, the relationship between you and Us, or any matters arising therefrom or associated therewith (whether contractual or otherwise) shall be subject to the exclusive jurisdiction of the courts of Israel.
                </p>
            </dl>
            <h2>XII. Violations</h2>
            <p>Any violations of Terms of Service may result in account termination.</p>

            <p><strong>Last Updated: May 27, 2017</strong>
        </p></div>
<?php require 'footer.php'; ?>